
export type User = {
  id: string;
  name: string;
  handle: string;
  headline: string;
  bio: string;
  avatar: string;
  coverImage: string;
  skills: string[];
  portfolio: string[];
  category: "design" | "writing" | "development";
  jobTitle?: string;
  company?: string;
  verified?: boolean;
  currentSession?: {
    workspaceName: string;
    with: string[]; // Array of user IDs
  };
};

export const placeholderUsers: User[] = [
  {
    id: "1",
    name: "Alice Johnson",
    handle: "alicej",
    headline: "UX/UI Designer | Creating Intuitive Digital Experiences",
    bio: "Passionate about crafting user-centric designs that are both beautiful and functional. 10+ years of experience in the tech industry.",
    avatar: "https://picsum.photos/seed/1027/200/200",
    coverImage: "https://picsum.photos/seed/cover1/1200/400",
    skills: ["UI/UX Design", "Figma", "Prototyping", "User Research", "Webflow"],
    portfolio: Array.from({ length: 6 }, (_, i) => `https://picsum.photos/seed/p1-${i}/400/300`),
    category: "design",
    jobTitle: "Principal Designer",
    company: "Creative Co.",
    verified: true,
  },
  {
    id: "2",
    name: "Bob Williams",
    handle: "bobw",
    headline: "Senior Frontend Developer | React & Next.js Expert",
    bio: "Building performant and scalable web applications. I love TypeScript and clean code. Always eager to learn new technologies.",
    avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw4fHxvY2VhbnxlbnwwfHx8fDE3NTcxMTMxODB8MA&ixlib=rb-4.1.0&q=80&w=1080",
    coverImage: "https://images.unsplash.com/photo-1518399681705-1c1a55e5e883?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxOXx8a2lsbGVyJTIwd2hhbGV8ZW58MHx8fHwxNzU3MTEyOTMzfDA&ixlib=rb-4.1.0&q=80&w=1080",
    skills: ["React", "Next.js", "TypeScript", "GraphQL", "Tailwind CSS"],
    portfolio: Array.from({ length: 6 }, (_, i) => `https://picsum.photos/seed/p2-${i}/400/300`),
    category: "development",
    jobTitle: "Senior Frontend Developer",
    company: "Innovate Inc.",
    verified: true,
  },
  {
    id: "3",
    name: "Charlie Brown",
    handle: "charlieb",
    headline: "Content Strategist & SEO Writer",
    bio: "Helping brands tell their story and rank higher on search engines. I specialize in long-form content for B2B SaaS companies.",
    avatar: "https://picsum.photos/seed/1011/200/200",
    coverImage: "https://picsum.photos/seed/cover3/1200/400",
    skills: ["Content Strategy", "SEO", "Copywriting", "Blogging", "Ahrefs"],
    portfolio: Array.from({ length: 6 }, (_, i) => `https://picsum.photos/seed/p3-${i}/400/300`),
    category: "writing",
    jobTitle: "Head of Content",
    company: "StoryWeavers",
    verified: true,
  },
  {
    id: "4",
    name: "Diana Prince",
    handle: "dianap",
    headline: "Full-Stack Developer | Node.js, Python, & Cloud",
    bio: "Architecting and building robust backend systems. Experienced with AWS and serverless architectures. Believer in DevOps culture.",
    avatar: "https://picsum.photos/seed/1012/200/200",
    coverImage: "https://picsum.photos/seed/cover4/1200/400",
    skills: ["Node.js", "Python", "AWS", "Serverless", "PostgreSQL"],
    portfolio: Array.from({ length: 6 }, (_, i) => `https://picsum.photos/seed/p4-${i}/400/300`),
    category: "development",
    currentSession: {
        workspaceName: "Project Phoenix",
        with: ["1"], // With Alice Johnson
    }
  },
  {
    id: "5",
    name: "Ethan Hunt",
    handle: "ethanh",
    headline: "Brand & Visual Designer",
    bio: "Creating memorable brand identities and visual systems. My work is driven by strategy and a passion for detail.",
    avatar: "https://picsum.photos/seed/1013/200/200",
    coverImage: "https://picsum.photos/seed/cover5/1200/400",
    skills: ["Branding", "Illustration", "Adobe Creative Suite", "Typography"],
    portfolio: Array.from({ length: 6 }, (_, i) => `https://picsum.photos/seed/p5-${i}/400/300`),
    category: "design",
  },
  {
    id: "6",
    name: "Fiona Glenanne",
    handle: "fionag",
    headline: "Technical Writer & Documentation Specialist",
    bio: "Making complex topics easy to understand. I write clear, concise, and comprehensive documentation for developers and end-users.",
    avatar: "https://picsum.photos/seed/1014/200/200",
    coverImage: "https://picsum.photos/seed/cover6/1200/400",
    skills: ["Technical Writing", "Docs-as-Code", "API Documentation", "Markdown"],
    portfolio: Array.from({ length: 6 }, (_, i) => `https://picsum.photos/seed/p6-${i}/400/300`),
    category: "writing",
    jobTitle: "Senior Technical Writer",
    company: "Clearly Documented",
    verified: true,
  },
];

export const placeholderPosts = [
  {
    id: 1,
    author: placeholderUsers[0],
    timestamp: "2h",
    content: `Just wrapped up a major redesign for a client's e-commerce platform. Focused on streamlining the checkout process and improving mobile navigation. The early feedback has been amazing! #UIDesign #UX`,
    image: "https://picsum.photos/seed/ui-ux-design/800/600",
    likes: 102,
    comments: 15,
    retweets: 23,
    views: "10.2k",
  },
  {
    id: 2,
    author: placeholderUsers[1],
    timestamp: "5h",
    content: `Excited to share that I'll be speaking at React Conf next month! I'll be diving deep into server components and the future of web development. Who else is going? #React #NextJS`,
    image: null,
    likes: 256,
    comments: 45,
    retweets: 88,
    views: "25.1k",
  },
  {
    id: 3,
    author: placeholderUsers[2],
    timestamp: "1d",
    content: `Published a new blog post on "The Ultimate Guide to SEO in 2024". It covers everything from keyword research to link building strategies. Hope you find it useful! Link in bio. #SEO #ContentMarketing`,
    image: "https://picsum.photos/seed/seo-guide/800/600",
    likes: 89,
    comments: 22,
    retweets: 41,
    views: "15.7k",
  },
  {
    id: 4,
    author: placeholderUsers[3],
    timestamp: "2d",
    content: `Just deployed a new microservice using serverless architecture on AWS. The performance gains are impressive, and the cost savings are even better. #serverless #aws #backend`,
    image: null,
    likes: 150,
    comments: 31,
    retweets: 50,
    views: "18.3k",
  },
  {
    id: 5,
    author: placeholderUsers[4],
    timestamp: "2d",
    content: `Experimenting with some new branding concepts for a client in the fintech space. Trying to balance a feeling of security with a modern, approachable vibe. It's a fun challenge! #branding #design #fintech`,
    image: "https://picsum.photos/seed/fintech-brand/800/600",
    likes: 95,
    comments: 12,
    retweets: 18,
    views: "8.9k",
  },
  {
    id: 6,
    author: placeholderUsers[5],
    timestamp: "3d",
    content: `My latest article on 'The Importance of Clear API Documentation' is now live. Good docs are a feature, not a chore. Check it out and let me know your thoughts! #techwriting #documentation #api`,
    image: "https://picsum.photos/seed/api-docs/800/600",
    likes: 72,
    comments: 18,
    retweets: 33,
    views: "7.1k",
  },
  {
    id: 7,
    author: placeholderUsers[1],
    timestamp: "3d",
    content: `What's your favorite utility for state management in React? I've been using Zustand a lot lately and loving its simplicity. #reactdev #javascript #statemanagement`,
    image: null,
    likes: 188,
    comments: 68,
    retweets: 45,
    views: "22.5k",
  },
  {
    id: 8,
    author: placeholderUsers[0],
    timestamp: "4d",
    content: `Thinking about accessibility from the start of a project is crucial. It's not an add-on, it's a core part of creating inclusive and effective products. What are your go-to a11y resources? #accessibility #a11y #uxdesign`,
    image: "https://picsum.photos/seed/accessibility/800/600",
    likes: 121,
    comments: 24,
    retweets: 30,
    views: "11.4k",
  },
  {
    id: 9,
    author: placeholderUsers[2],
    timestamp: "5d",
    content: `The key to great B2B content is understanding the customer's pain points inside and out. Don't just sell features, sell solutions to their problems. #b2bmarketing #contentstrategy`,
    image: null,
    likes: 65,
    comments: 9,
    retweets: 21,
    views: "6.8k",
  },
  {
    id: 10,
    author: placeholderUsers[3],
    timestamp: "5d",
    content: `Refactoring a legacy codebase can be daunting, but so rewarding. Finding those small wins and performance improvements is the best feeling. #coding #softwaredevelopment #python`,
    image: "https://picsum.photos/seed/refactoring/800/600",
    likes: 133,
    comments: 29,
    retweets: 35,
    views: "14.9k",
  },
  {
    id: 11,
    author: placeholderUsers[4],
    timestamp: "6d",
    content: `A powerful logo is more than just a pretty picture; it's the cornerstone of a brand's identity. It should be simple, memorable, and timeless. #logodesign #branding`,
    image: null,
    likes: 210,
    comments: 35,
    retweets: 60,
    views: "20.1k",
  },
  {
    id: 12,
    author: placeholderUsers[5],
    timestamp: "1w",
    content: `Great documentation empowers users and reduces support tickets. It's an investment that pays for itself over and over. #technicalwriting #userguides`,
    image: null,
    likes: 55,
    comments: 11,
    retweets: 25,
    views: "5.2k",
  },
  {
    id: 13,
    author: placeholderUsers[0],
    timestamp: "1w",
    content: `Just finished a user research sprint for a new mobile app. The insights we gathered are going to be a game-changer for the product roadmap. Never underestimate the power of talking to your users! #userresearch #ux`,
    image: "https://picsum.photos/seed/user-research/800/600",
    likes: 142,
    comments: 19,
    retweets: 41,
    views: "13.5k",
  },
  {
    id: 14,
    author: placeholderUsers[1],
    timestamp: "1w",
    content: `The new features in Next.js 15 are looking incredible. The team is really pushing the boundaries of what's possible on the web. Can't wait to start building with it. #webdev #nextjs`,
    image: "https://picsum.photos/seed/nextjs-15/800/600",
    likes: 301,
    comments: 55,
    retweets: 110,
    views: "35.6k",
  },
  {
    id: 15,
    author: placeholderUsers[3],
    timestamp: "2w",
    content: `Setting up a new CI/CD pipeline with GitHub Actions. The level of automation you can achieve is fantastic for team productivity. #devops #cicd #github`,
    image: null,
    likes: 98,
    comments: 14,
    retweets: 28,
    views: "9.1k",
  },
  {
    id: 16,
    author: placeholderUsers[2],
    timestamp: "2w",
    content: `What are your best tips for beating writer's block? My go-to is to step away from the screen and go for a long walk. It works wonders! #writing #creativity`,
    image: "https://picsum.photos/seed/writers-block/800/600",
    likes: 78,
    comments: 34,
    retweets: 19,
    views: "7.7k",
  },
];

export const placeholderMessages = [
  {
    id: "msg1",
    userId: "2",
    messages: [
      { from: "2", text: "Hey Alice, saw your profile on Sentry. Your design work is incredible!", time: "10:30 AM" },
      { from: "me", text: "Thanks, Bob! I appreciate that. Your frontend projects look really solid.", time: "10:31 AM" },
      { from: "2", text: "I'm looking for a designer for a new side project. It's a mobile app for local event discovery. Would you be interested in hearing more?", time: "10:32 AM" },
    ],
  },
   {
    id: "msg2",
    userId: "3",
    messages: [
      { from: "3", text: "Hi there! I'm looking for a developer to help build out a new blog. Your experience with Next.js seems like a perfect fit.", time: "Yesterday" },
      { from: "me", text: "Hi Charlie. Happy to chat. What kind of features are you looking for?", time: "Yesterday" },
    ],
  },
];

export const placeholderNews = [
    {
        id: "1",
        category: "AI & Machine Learning",
        title: "AI Startup 'Innovate' Raises $50M Series B to Revolutionize Code Generation",
        author: "Alex Chen",
        date: "2 hours ago",
        excerpt: "Innovate, a company building AI-powered tools for developers, announced today it has closed a $50 million Series B funding round led by Future Ventures.",
        imageUrl: "https://picsum.photos/seed/news1/600/400",
    },
    {
        id: "2",
        category: "Platforms",
        title: "Connective Unveils 'Sentry', a New Platform for Creative Professionals to Network and Collaborate",
        author: "Maria Rodriguez",
        date: "1 day ago",
        excerpt: "The professional networking space gets a new contender today with the launch of Sentry, a platform designed specifically for freelancers and creatives.",
        imageUrl: "https://picsum.photos/seed/news2/600/400",
    },
    {
        id: "3",
        category: "Freelance",
        title: "The Rise of 'Micro-Teams': How Freelancers are Shaping the Future of Work",
        author: "David Smith",
        date: "3 days ago",
        excerpt: "Forget the traditional 9-to-5. A new trend is emerging where elite freelancers form small, agile teams to tackle complex projects for major corporations.",
        imageUrl: "https://picsum.photos/seed/news3/600/400",
    },
     {
        id: "4",
        category: "UI/UX",
        title: "Is Neobrutalism the Future of UI Design? A Deep Dive.",
        author: "Emily White",
        date: "4 days ago",
        excerpt: "Characterized by raw elements, bold typography, and a stark honesty, neobrutalism is taking the design world by storm. We explore its origins and impact.",
        imageUrl: "https://picsum.photos/seed/news4/600/400",
    },
    {
        id: "5",
        category: "Freelance",
        title: "How to Price Your Services as a Creative Freelancer",
        author: "John Doe",
        date: "5 days ago",
        excerpt: "Struggling to figure out your rates? This guide breaks down the different pricing models and helps you find the one that works for you.",
        imageUrl: "https://picsum.photos/seed/news5/600/400",
    },
    {
        id: "6",
        category: "Writing",
        title: "The Art of Storytelling in Brand Marketing",
        author: "Jane Austen",
        date: "6 days ago",
        excerpt: "Discover how to craft compelling narratives that resonate with your audience and build lasting brand loyalty. It's not just about what you sell, but the story you tell.",
        imageUrl: "https://picsum.photos/seed/news6/600/400",
    },
    {
        id: "7",
        category: "Development",
        title: "A Guide to State Management in Modern React Applications",
        author: "Ada Lovelace",
        date: "1 week ago",
        excerpt: "From Zustand to Jotai, we explore the landscape of state management libraries in the React ecosystem beyond Redux.",
        imageUrl: "https://picsum.photos/seed/news7/600/400",
    },
    {
        id: "8",
        category: "Cybersecurity",
        title: "Protecting Your Digital Assets: A Guide for Freelancers",
        author: "Alan Turing",
        date: "1 week ago",
        excerpt: "As a freelancer, you're a target. Learn how to secure your devices, data, and client information from cyber threats.",
        imageUrl: "https://picsum.photos/seed/news8/600/400",
    },
    {
        id: "9",
        category: "Data Science",
        title: "The Impact of Big Data on Creative Industries",
        author: "Grace Hopper",
        date: "2 weeks ago",
        excerpt: "Data is not just for tech companies. See how creatives are using data to inform their work, from film production to music composition.",
        imageUrl: "https://picsum.photos/seed/news9/600/400",
    },
    {
        id: "10",
        category: "Cloud Computing",
        title: "Serverless for Startups: A Cost-Effective Approach to Scaling",
        author: "Vint Cerf",
        date: "2 weeks ago",
        excerpt: "Learn how serverless architectures can help your startup scale without breaking the bank on infrastructure costs.",
        imageUrl: "https://picsum.photos/seed/news10/600/400",
    },
    {
        id: "11",
        category: "Events",
        title: "Design Forward 2024: A Recap of the Biggest Announcements",
        author: "Casey Newton",
        date: "Yesterday",
        excerpt: "From AI-powered design tools to the latest trends in sustainable design, here's everything you missed from this year's landmark conference.",
        imageUrl: "https://picsum.photos/seed/news11/600/400",
    },
    {
        id: "12",
        category: "Spotlight",
        title: "From Side Project to Unicorn: The Story of Sentry",
        author: "Kara Swisher",
        date: "2 days ago",
        excerpt: "An in-depth look at how a small team of developers and designers built a platform that's changing the game for creative professionals.",
        imageUrl: "https://picsum.photos/seed/news12/600/400",
    },
    {
        id: "13",
        category: "Tech",
        title: "Quantum Computing: What Creatives Need to Know",
        author: "Ben Goertzel",
        date: "3 weeks ago",
        excerpt: "Quantum computing isn't just for scientists. We explore how this emerging technology could revolutionize creative fields from design to music.",
        imageUrl: "https://picsum.photos/seed/news13/600/400",
    },
    {
        id: "14",
        category: "Design",
        title: "The Psychology of Color in Branding",
        author: "Jessica Walsh",
        date: "3 weeks ago",
        excerpt: "A deep dive into how color theory influences consumer perception and how to choose the perfect palette for your brand.",
        imageUrl: "https://picsum.photos/seed/news14/600/400",
    },
    {
        id: "15",
        category: "Development",
        title: "WebAssembly: The Future of High-Performance Web Apps",
        author: "Brendan Eich",
        date: "4 weeks ago",
        excerpt: "Is JavaScript's reign ending? We explore how WebAssembly is enabling near-native performance for web applications.",
        imageUrl: "https://picsum.photos/seed/news15/600/400",
    },
    {
        id: "16",
        category: "Freelance",
        title: "Navigating the Gig Economy: How to Stand Out",
        author: "Sara Horowitz",
        date: "1 month ago",
        excerpt: "The founder of the Freelancers Union shares her tips for thriving in the competitive gig economy and building a sustainable career.",
        imageUrl: "https://picsum.photos/seed/news16/600/400",
    }
];

export const placeholderCourses = [
    {
        id: "course1",
        title: "Advanced TypeScript for Modern Applications",
        author: "Bob Williams",
        price: 149.99,
        category: "Development",
        description: "Take your TypeScript skills to the next level. Learn advanced patterns, decorators, and how to build type-safe, enterprise-grade applications.",
        imageUrl: "https://picsum.photos/seed/course1/600/400",
        level: "Advanced",
    },
    {
        id: "course2",
        title: "Figma Mastery: From Beginner to Pro",
        author: "Alice Johnson",
        price: 99.99,
        category: "Design",
        description: "A comprehensive guide to Figma. Master components, auto layout, and prototyping to create stunning and efficient designs.",
        imageUrl: "https://picsum.photos/seed/course2/600/400",
        level: "Beginner",
    },
    {
        id: "course3",
        title: "SEO-Driven Content Strategy",
        author: "Charlie Brown",
        price: 199.99,
        category: "Writing",
        description: "Learn how to create a content strategy that drives organic traffic. This course covers keyword research, on-page SEO, and content promotion.",
        imageUrl: "https://picsum.photos/seed/course3/600/400",
        level: "Intermediate",
    },
     {
        id: "course4",
        title: "Building Serverless APIs with Node.js",
        author: "Diana Prince",
        price: 129.99,
        category: "Development",
        description: "Learn how to build, deploy, and scale serverless APIs on AWS using Node.js, API Gateway, and Lambda. No servers, no problem.",
        imageUrl: "https://picsum.photos/seed/course4/600/400",
        level: "Intermediate",
    },
    {
        id: "course5",
        title: "Introduction to Generative AI",
        author: "Alan Turing",
        price: 249.99,
        category: "AI & Machine Learning",
        description: "Explore the fundamentals of generative AI, including large language models, diffusion models, and their applications.",
        imageUrl: "https://picsum.photos/seed/course5/600/400",
        level: "Beginner",
    },
    {
        id: "course6",
        title: "Practical Data Science with Python",
        author: "Grace Hopper",
        price: 179.99,
        category: "Data Science",
        description: "Get hands-on experience with Pandas, Scikit-learn, and Matplotlib to analyze data and build predictive models.",
        imageUrl: "https://picsum.photos/seed/course6/600/400",
        level: "Intermediate",
    },
];

export const placeholderPodcasts = [
    {
        id: "podcast1",
        title: "The Design Details Podcast",
        author: "Alice Johnson & Ethan Hunt",
        category: "Design",
        description: "A weekly podcast about the details of design. We dive into the latest trends, tools, and challenges facing designers today.",
        imageUrl: "https://picsum.photos/seed/podcast1/600/400",
    },
    {
        id: "podcast2",
        title: "Code & Coffee",
        author: "Bob Williams",
        category: "Development",
        description: "A morning show for developers. Join Bob as he discusses the latest news in the world of web development, from new frameworks to career advice.",
        imageUrl: "https://picsum.photos/seed/podcast2/600/400",
    },
    {
        id: "podcast3",
        title: "The Freelance Journey",
        author: "Fiona Glenanne",
        category: "Freelance",
        description: "Interviews with successful freelancers from various fields. Learn about their journey, challenges, and what it takes to succeed on your own.",
        imageUrl: "https://picsum.photos/seed/podcast3/600/400",
    },
    {
        id: "podcast4",
        title: "Cyber Chats",
        author: "Alan Turing",
        category: "Cybersecurity",
        description: "A podcast dedicated to the world of cybersecurity. We discuss the latest threats, vulnerabilities, and how to stay safe in a digital world.",
        imageUrl: "https://picsum.photos/seed/podcast4/600/400",
    },
    {
        id: "podcast5",
        title: "UI/UX Insights",
        author: "Alice Johnson",
        category: "UI/UX",
        description: "Deep dives into user interface and user experience design principles, case studies, and interviews with industry leaders.",
        imageUrl: "https://picsum.photos/seed/podcast5/600/400",
    },
];
