-- Create a table for ad campaigns
create table campaigns (
    id bigint generated by default as identity primary key,
    user_id uuid references auth.users on delete cascade not null,
    name text not null,
    status text not null,
    type text not null,
    spend integer not null,
    conversions integer not null,
    created_at timestamp with time zone default now() not null
);

alter table campaigns
enable row level security;

create policy "Users can manage their own campaigns." on campaigns
for all using (auth.uid() = user_id);

-- Seed data for campaigns
insert into campaigns (user_id, name, status, type, spend, conversions)
select id, 'Summer Sale Promotion', 'Active', 'Sponsored Content', 500, 25 from auth.users limit 1;

insert into campaigns (user_id, name, status, type, spend, conversions)
select id, 'Freelancer Profile Boost', 'Active', 'Profile Spotlight', 150, 120 from auth.users limit 1;

insert into campaigns (user_id, name, status, type, spend, conversions)
select id, 'New Product Launch', 'Paused', 'Product Listing', 1200, 88 from auth.users limit 1;

insert into campaigns (user_id, name, status, type, spend, conversions)
select id, 'Tech Blog Sponsored Post', 'Finished', 'Sponsored Content', 800, 450 from auth.users limit 1;
